server:
  port: 10720

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.24.22.139:8721/lottery?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456

    type: com.alibaba.druid.pool.DruidDataSource
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true
    filters: stat,wall,log4j
    testOnBorrow: false
    maxActive: 20
    validationQuery: SELECT 1 FROM DUAL
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    maxWait: 60000
    testOnReturn: false
    minIdle: 5
    maxPoolPreparedStatementPerConnectionSize: 20
    initialSize: 5
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://10.204.125.109:8863/eureka/

mybatis-plus:
  # 扫描mapper.xml文件
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 扫描实体类
  typeAliasesPackage: com.wjs.lottery.*.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 0 #逻辑删除值 默认1
      logic-not-delete-value: 1 #逻辑未删除值 默认 0
      logic-delete-field: valid #全局逻辑删除字段 或者在实体字段上配置 @TableLogic