spring:
  profiles:
    active: dev
  application:
    name: module-seata4
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 10.204.125.109:8848
