server:
  port: 10681

spring:
  kafka:
    bootstrap-servers: 10.204.125.254:9092,10.204.125.254:9093,10.204.125.254:9094
    #bootstrap-servers: 192.168.2.103:9092
    producer:
      #消息不足时，发送消息间隔 单位毫秒
      linger: 100
      #重试
      retries: 0
      #默认值是16KB
      batch-size: 16384
      #发送缓冲取，默认32M
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: user-log-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      concurrency: 2


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://10.204.125.109:8863/eureka/

wechat:
  minis:
    - appid: wxeb20873968183f4c
      secret: 105a9574e4ff17f6978a2f25d853442e
      grant_type: authorization_code
      roles:
        - ababab
    - appid: wxeb20873968183f4c
      secret: 105a9574e4ff17f6978a2f25d853442e
      grant_type: authorization_code
      roles:
        - ababab
