server:
  port: 10680
spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许携带认证信息
            # 允许跨域的源(网站域名/ip)，设置*为全部
            # 允许跨域请求里的head字段，设置*为全部
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            # 跨域允许的有效期
            allow-credentials: true
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods: "*"
            max-age: 3600
      routes:
        - id: designer-service
          uri: lb://designer-service
          predicates:
            - Path=/designer/**
          filters:
            - StripPrefix=1
        #   - SaveSession

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://10.204.125.109:8863/eureka/
